from PyroUbot.core.plugins.adb import *
from PyroUbot.core.plugins.adm import *
from PyroUbot.core.plugins.alv import *
from PyroUbot.core.plugins.anm import *
from PyroUbot.core.plugins.asp import *
from PyroUbot.core.plugins.btn import *
from PyroUbot.core.plugins.cpy import *
from PyroUbot.core.plugins.ctr import *
from PyroUbot.core.plugins.cvr import *
from PyroUbot.core.plugins.dbf import *
from PyroUbot.core.plugins.evl import *
from PyroUbot.core.plugins.fnt import *
from PyroUbot.core.plugins.gcs import *
from PyroUbot.core.plugins.ggl import *
from PyroUbot.core.plugins.gpw import *
from PyroUbot.core.plugins.hlp import *
from PyroUbot.core.plugins.img import *
from PyroUbot.core.plugins.ivt import *
from PyroUbot.core.plugins.kng import *
from PyroUbot.core.plugins.lgo import *
from PyroUbot.core.plugins.lmt import *
from PyroUbot.core.plugins.mmf import *
from PyroUbot.core.plugins.mms import *
from PyroUbot.core.plugins.nts import *
from PyroUbot.core.plugins.ocr import *
from PyroUbot.core.plugins.pgr import *
from PyroUbot.core.plugins.pyn import *
from PyroUbot.core.plugins.qrq import *
from PyroUbot.core.plugins.qtl import *
from PyroUbot.core.plugins.rts import *
from PyroUbot.core.plugins.sct import *
from PyroUbot.core.plugins.sid import *
from PyroUbot.core.plugins.smd import *
from PyroUbot.core.plugins.smt import *
from PyroUbot.core.plugins.spm import *
from PyroUbot.core.plugins.spt import *
from PyroUbot.core.plugins.srh import *
from PyroUbot.core.plugins.stf import *
from PyroUbot.core.plugins.stg import *
from PyroUbot.core.plugins.str import *
from PyroUbot.core.plugins.tll import *
from PyroUbot.core.plugins.tny import *
from PyroUbot.core.plugins.tph import *
from PyroUbot.core.plugins.trl import *
from PyroUbot.core.plugins.whs import *
from PyroUbot.core.plugins.wrt import *
from PyroUbot.core.plugins.ytp import *
from PyroUbot.core.plugins.zbs import *
